#
# ~/.tmux.conf
#
# Last configured for tmux 2.5

#---------.
# OPTIONS |
#---------'
# use vi keys while navigating a buffer
setw -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Mouse mode for me, a wimp
set -g mouse on


#----------.
# KEYBINDS |
#----------'
# Unbind some defaults
# --------------------
unbind C-b

# Ctrl+Space to send commands
set -g prefix C-Space
bind C-Space send-prefix

# vim-like copy and paste
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# look at this nonsense
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xsel -i -p && xsel -o -p | xsel -i -b'


#------------.
# STATUS BAR |
#------------'
#eh

#---------.
# PLUGINS |
#---------'
# TMUX Plugin Manager
#set -g @plugin 'tmux-plugins/tpm'

# A sensible set of default options
#set -g @plugin 'tmux-plugins/tmux-sensible'

# Vim-like pane navigation
#set -g @plugin 'tmux-plugins/tmux-pain-control'


# Initialize TMUX plugin manager 
# keep this line at the very bottom of tmux.conf
#run '~/.tmux/plugins/tpm/tpm'
