#
# ~/.tmux.conf
#

#---------.
# OPTIONS |
#---------'
# Each new pane runs an interactive shell, not a login shell
set-option -g default-command $SHELL

# Use vi keys while navagating a buffer
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Mouse mode for me, a wimp
set -g mouse on


#----------.
# KEYBINDS |
#----------'
# Ctrl+Space to send commands
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Enter copy mode with ` (Grave accent key) and use vi commands
unbind [
bind ` copy-mode
unbind p
bind p paste-buffer
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-pipe 'xsel -b' #use system clipboard 
bind-key -t vi-copy 'C-v' rectangle-toggle  #block selection
bind-key -t vi-copy 'Escape' cancel


#------------.
# STATUS BAR |
#------------'
# Use vim's tmuxline generated status line
source ~/.tmux/tmuxline.conf


#---------.
# PLUGINS |
#---------'
# TMUX Plugin Manager
set -g @plugin 'tmux-plugins/tpm'

# A sensible set of default options
set -g @plugin 'tmux-plugins/tmux-sensible'

# Vim-like pane navigation
set -g @plugin 'tmux-plugins/tmux-pain-control'


# Initialize TMUX plugin manager 
# keep this line at the very bottom of tmux.conf
run '~/.tmux/plugins/tpm/tpm'
